### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by codebosss**
-Make page responsive
-Increase image dimensions
-Correct css file location

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
@codebosss  which issue does this PR Solve ?

**Comment by ceoshikhar** [comment]
> @codebosss which issue does this PR Solve ?

It solves #9

**Comment by YashKumarVerma** [comment]
Please resolve conflicts. (this is something that you actually have to learn in github)

**Comment by codebosss** [comment]
Conflict resolved.Please check.

**Pull request merged**
