### PR TITLE
Fixed broken path of arpit.jpg

### PR DESCRIPTION
**Pull request by vipul1999**
#43 Fixed broken path of arpit.jpg

### CODE REVIEW

**Comment by YashKumarVerma** [comment]
Send PR from new branch. Too many commits in this one.

**Comment by vipul1999** [comment]
Every time I create a branch or pull again from upstream(main repo). It consists of my old commits. I seem not to able to get rid of them. I tried to cherry-picking commits but It is too complicated for me.
I will need help here.

**Comment by YashKumarVerma** [comment]
delete fork, form again, use pull bot, create new branch, make changes, send PR.

**Comment by YashKumarVerma** [comment]
Already fixed.

**Pull request closed without merging**
